import { useMemo, useState } from 'react';
import { Barcode, QrCode, Wand2, Keyboard, Trash2, Plus, ShieldCheck } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { toast } from '../components/ui/Toast';
import { useBarcodeScanner } from '../hooks/useBarcodeScanner';
import { LabelLayoutPanel, useLabelSetup, cleanError } from '../components/labels/LabelLayoutPanel';
import { SYMBOLOGIES, symbology, normalizeCode } from '../lib/barcodes';
import { t } from '../i18n';

const clampInt = (value, min, max) => Math.min(max, Math.max(min, parseInt(value, 10) || min));

/**
 * Free barcodes: labels that are not tied to an article yet (a roll of
 * stickers to put on clothes and scan into articles later, shelf or box
 * labels…). Codes are generated by the app from a reserved sequence, so the
 * same code is never handed out twice, and every code is checked against the
 * articles, variants and gift cards before it is printed.
 */
export default function BarcodeLabelPage() {
    const setup = useLabelSetup();
    const [type, setType] = useState('ean13');
    const [mode, setMode] = useState('auto');
    const [count, setCount] = useState(10);
    const [copies, setCopies] = useState(1);
    const [manual, setManual] = useState('');
    const [title, setTitle] = useState('');
    const [price, setPrice] = useState('');
    const [codes, setCodes] = useState([]); // { code, symbology, copies }
    const [busy, setBusy] = useState(false);

    const spec = symbology(type);

    const generate = async () => {
        setBusy(true);
        try {
            const created = await window.electronAPI.catalog.generateFreeCodes(type, clampInt(count, 1, 500), codes.map(c => c.code));
            setCodes(prev => [...prev, ...created.map(code => ({ code, symbology: type, copies: clampInt(copies, 1, 100) }))]);
            toast.success(t('labels.freeGenerated', { n: created.length }));
        } catch (error) {
            toast.error(cleanError(error));
        } finally {
            setBusy(false);
        }
    };

    // Typed or scanned codes: fix the format, then refuse codes already in use
    const addCodes = async (lines) => {
        const accepted = [];
        const errors = [];
        for (const line of lines.map(l => l.trim()).filter(Boolean)) {
            const result = normalizeCode(type, line);
            if (result.error) errors.push(`${line}: ${t(result.error, result.params)}`);
            else if (codes.some(c => c.code === result.code) || accepted.includes(result.code)) errors.push(`${line}: ${t('labels.err.inList')}`);
            else accepted.push(result.code);
        }
        let used = [];
        if (accepted.length) {
            used = await window.electronAPI.catalog.findUsedCodes(accepted);
            used.forEach(code => errors.push(`${code}: ${t('labels.err.used')}`));
        }
        const fresh = accepted.filter(code => !used.includes(code));
        if (fresh.length) {
            setCodes(prev => [...prev, ...fresh.map(code => ({ code, symbology: type, copies: clampInt(copies, 1, 100) }))]);
            toast.success(t('labels.codesAdded', { n: fresh.length }));
        }
        if (errors.length) toast.error(errors.slice(0, 4).join('\n') + (errors.length > 4 ? '\n…' : ''));
        return fresh.length > 0 || errors.length === 0;
    };

    useBarcodeScanner((code) => { if (mode === 'manual') addCodes([code]); });

    const items = useMemo(() => codes.map(c => ({
        code: c.code, symbology: c.symbology, title, price, quantity: c.copies,
    })), [codes, title, price]);
    const totalLabels = codes.reduce((sum, c) => sum + c.copies, 0);

    // Last check right before printing: a code may have been given to an article meanwhile
    const beforePrint = async () => {
        const used = await window.electronAPI.catalog.findUsedCodes(codes.map(c => c.code));
        if (used.length) {
            toast.error(t('labels.usedBeforePrint', { codes: used.slice(0, 5).join(', ') }));
            return null;
        }
        return items;
    };

    const fields = [
        ['showShopName', t('labels.showShopName')],
        ['showProductName', t('labels.freeTitleField')],
        ['showPrice', t('labels.showPrice')],
        ...(spec.kind === '2D' ? [['showSku', t('labels.codeUnder')]] : []),
    ];

    return (
        <div className="h-full grid grid-cols-1 lg:grid-cols-12 overflow-hidden">
            <div className="lg:col-span-7 overflow-y-auto p-4 space-y-4 border-e border-dark-border min-h-0">
                {/* 1. Type */}
                <section className="card p-4">
                    <h3 className="font-semibold mb-3">{t('labels.step1')}</h3>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                        {SYMBOLOGIES.map(s => (
                            <button key={s.id} type="button" onClick={() => setType(s.id)}
                                className={`p-3 rounded-lg border text-start transition-colors ${type === s.id
                                    ? 'border-indigo-500 bg-indigo-500/10'
                                    : 'border-dark-border bg-dark-tertiary/40 hover:border-zinc-600'}`}>
                                <div className="flex items-center gap-2 font-medium">
                                    {s.kind === '2D' ? <QrCode className="w-4 h-4 text-indigo-300" /> : <Barcode className="w-4 h-4 text-indigo-300" />}
                                    <span className="ltr">{s.name}</span>
                                </div>
                                <p className="text-xs text-zinc-500 mt-1 leading-snug">{t(s.hint)}</p>
                            </button>
                        ))}
                    </div>
                </section>

                {/* 2. Codes */}
                <section className="card p-4 space-y-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                        <h3 className="font-semibold">{t('labels.step2')}</h3>
                        <div className="segmented">
                            <button type="button" className={`inline-flex items-center gap-1.5 ${mode === 'auto' ? 'active' : ''}`} onClick={() => setMode('auto')}>
                                <Wand2 className="w-4 h-4" /> {t('labels.modeAuto')}
                            </button>
                            <button type="button" className={`inline-flex items-center gap-1.5 ${mode === 'manual' ? 'active' : ''}`} onClick={() => setMode('manual')}>
                                <Keyboard className="w-4 h-4" /> {t('labels.modeManual')}
                            </button>
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                        {mode === 'auto' && (
                            <div className="form-group">
                                <label className="form-label">{t('labels.howMany')}</label>
                                <input type="number" min="1" max="500" className="input tabular" value={count} onChange={(e) => setCount(e.target.value)} />
                            </div>
                        )}
                        <div className="form-group">
                            <label className="form-label">{t('labels.copiesEach')}</label>
                            <input type="number" min="1" max="100" className="input tabular" value={copies} onChange={(e) => setCopies(e.target.value)} />
                        </div>
                    </div>

                    {mode === 'auto' ? (
                        <Button onClick={generate} loading={busy} className="w-full">
                            <Wand2 className="w-4 h-4" /> {t('labels.generateN', { n: clampInt(count, 1, 500), type: spec.name })}
                        </Button>
                    ) : (
                        <div className="space-y-2">
                            <textarea rows={3} className="input h-auto py-2 ltr font-mono text-sm" value={manual}
                                onChange={(e) => setManual(e.target.value)} placeholder={t('labels.manualPlaceholder')} data-scan-passthrough />
                            <Button variant="secondary" className="w-full" onClick={async () => { if (await addCodes(manual.split(/[\n,;]+/))) setManual(''); }}>
                                <Plus className="w-4 h-4" /> {t('labels.addCodes')}
                            </Button>
                        </div>
                    )}
                    <p className="form-hint flex items-start gap-1.5"><ShieldCheck className="w-4 h-4 text-emerald-400 flex-none" /> {t('labels.uniqueHint')}</p>
                </section>

                {/* 3. Text on the label */}
                <section className="card p-4">
                    <h3 className="font-semibold mb-3">{t('labels.step3')}</h3>
                    <div className="grid grid-cols-2 gap-3">
                        <div className="form-group">
                            <label className="form-label">{t('labels.freeTitle')}</label>
                            <input className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder={t('labels.freeTitlePlaceholder')} />
                        </div>
                        <div className="form-group">
                            <label className="form-label">{t('labels.freePrice')}</label>
                            <input type="number" min="0" className="input tabular" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="—" />
                        </div>
                    </div>
                </section>

                {/* Codes ready to print */}
                <section className="card overflow-hidden">
                    <div className="px-4 py-3 border-b border-dark-border flex items-center justify-between">
                        <h3 className="font-semibold">{t('labels.toPrint', { n: codes.length })}</h3>
                        {codes.length > 0 && <Button variant="ghost" size="sm" onClick={() => setCodes([])}>{t('qr.clear')}</Button>}
                    </div>
                    {codes.length === 0 ? (
                        <p className="p-6 text-center text-sm text-zinc-500">{t('labels.noCodes')}</p>
                    ) : (
                        <div className="max-h-72 overflow-y-auto divide-y divide-dark-border">
                            {codes.map(c => (
                                <div key={c.code} className="px-4 py-2 flex items-center gap-3">
                                    <span className="badge bg-dark-tertiary text-zinc-300 ltr">{symbology(c.symbology).name}</span>
                                    <span className="flex-1 font-mono text-sm ltr text-start">{c.code}</span>
                                    <input type="number" min="1" max="100" className="input input-sm w-20 tabular" value={c.copies} aria-label={t('labels.copiesEach')}
                                        onChange={(e) => setCodes(prev => prev.map(x => (x.code === c.code ? { ...x, copies: clampInt(e.target.value, 1, 100) } : x)))} />
                                    <button type="button" onClick={() => setCodes(prev => prev.filter(x => x.code !== c.code))}
                                        className="p-1.5 rounded hover:bg-red-500/15 text-red-300" aria-label={t('common.delete')}>
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}
                </section>
            </div>

            <div className="lg:col-span-5 overflow-y-auto p-4">
                <LabelLayoutPanel setup={setup} items={items} totalLabels={totalLabels} fields={fields} beforePrint={beforePrint} />
            </div>
        </div>
    );
}
